# Generated by Django 5.2 on 2025-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Mobileno', models.CharField(max_length=15, unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=6)),
                ('Gender', models.CharField(default='Male', max_length=10)),
                ('Usertype', models.CharField(default='NA', max_length=20)),
                ('Cause', models.CharField(default='NA', max_length=200)),
                ('Age', models.CharField(default='NA', max_length=3)),
                ('Insurance', models.CharField(default='NA', max_length=100)),
                ('Specialization', models.CharField(default='NA', max_length=150)),
                ('Availability', models.CharField(default='NA', max_length=50)),
                ('Experience', models.CharField(default='NA', max_length=30)),
                ('Created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
