# Generated by Django 5.2 on 2025-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(default=3, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
